[package]
name = "pass-search"
version = "0.1.0"
authors = ["Vickenty Fesunov <kent@setattr.net>"]
license = "GPL-2.0-or-later"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbus="0.8"
anyhow="1.0"
walkdir="2.3"
